// Generated by scripts/import-confessions.ts. Do not edit by hand.
import type { ConfessionDocument } from './types';

/**
 * Native only. `require` is lazy per module in Metro, so a confession is
 * parsed the first time it is actually opened rather than at startup. The web
 * build fetches the same files from `public/` instead — see loader.web.ts.
 */
export const CONFESSION_FILES: Record<string, () => ConfessionDocument> = {
  "wsc": () => require('./wsc.json') as ConfessionDocument,
  "heidelberg": () => require('./heidelberg.json') as ConfessionDocument,
  "wcf": () => require('./wcf.json') as ConfessionDocument,
  "belgic": () => require('./belgic.json') as ConfessionDocument,
  "dort": () => require('./dort.json') as ConfessionDocument,
  "young-children": () => require('./young-children.json') as ConfessionDocument,
  "lbcf-1689": () => require('./lbcf-1689.json') as ConfessionDocument,
  "keach": () => require('./keach.json') as ConfessionDocument,
  "apostles-creed": () => require('./apostles-creed.json') as ConfessionDocument,
  "nicene-creed": () => require('./nicene-creed.json') as ConfessionDocument,
  "athanasian-creed": () => require('./athanasian-creed.json') as ConfessionDocument,
  "chalcedon": () => require('./chalcedon.json') as ConfessionDocument,
  "council-of-orange": () => require('./council-of-orange.json') as ConfessionDocument,
  "wlc": () => require('./wlc.json') as ConfessionDocument,
  "second-helvetic": () => require('./second-helvetic.json') as ConfessionDocument,
  "french-confession": () => require('./french-confession.json') as ConfessionDocument,
  "scots-confession": () => require('./scots-confession.json') as ConfessionDocument,
  "consensus-tigurinus": () => require('./consensus-tigurinus.json') as ConfessionDocument,
  "tetrapolitan": () => require('./tetrapolitan.json') as ConfessionDocument,
  "zwingli-67": () => require('./zwingli-67.json') as ConfessionDocument,
  "zwingli-fidei": () => require('./zwingli-fidei.json') as ConfessionDocument,
  "first-helvetic": () => require('./first-helvetic.json') as ConfessionDocument,
  "first-basel": () => require('./first-basel.json') as ConfessionDocument,
  "waldensian": () => require('./waldensian.json') as ConfessionDocument,
  "berne-theses": () => require('./berne-theses.json') as ConfessionDocument,
  "abstract-principles": () => require('./abstract-principles.json') as ConfessionDocument,
  "matthew-henry": () => require('./matthew-henry.json') as ConfessionDocument,
  "puritan-catechism": () => require('./puritan-catechism.json') as ConfessionDocument,
  "assemblies-exposition": () => require('./assemblies-exposition.json') as ConfessionDocument,
  "shorter-explained": () => require('./shorter-explained.json') as ConfessionDocument,
  "baptist-catechism": () => require('./baptist-catechism.json') as ConfessionDocument,
  "gregory-declaration": () => require('./gregory-declaration.json') as ConfessionDocument,
  "irenaeus-rule": () => require('./irenaeus-rule.json') as ConfessionDocument,
  "tertullian-rule": () => require('./tertullian-rule.json') as ConfessionDocument,
  "ignatius-creed": () => require('./ignatius-creed.json') as ConfessionDocument,
};
