// Generated by scripts/import-confessions.ts. Do not edit by hand.

/**
 * Sources with an imported document, on both platforms. Separate from
 * confessionMap.generated.ts because that file's `require` calls would pull
 * every document into the web bundle.
 */
export const CONFESSION_IDS: ReadonlySet<string> = new Set([
  "wsc",
  "heidelberg",
  "wcf",
  "belgic",
  "dort",
  "young-children",
  "lbcf-1689",
  "keach",
  "apostles-creed",
  "nicene-creed",
  "athanasian-creed",
  "chalcedon",
  "council-of-orange",
  "wlc",
  "second-helvetic",
  "french-confession",
  "scots-confession",
  "consensus-tigurinus",
  "tetrapolitan",
  "zwingli-67",
  "zwingli-fidei",
  "first-helvetic",
  "first-basel",
  "waldensian",
  "berne-theses",
  "abstract-principles",
  "matthew-henry",
  "puritan-catechism",
  "assemblies-exposition",
  "shorter-explained",
  "baptist-catechism",
  "gregory-declaration",
  "irenaeus-rule",
  "tertullian-rule",
  "ignatius-creed",
]);
